### ISSUE TITLE
Crear pantalla de créditos

### ISSUE THREAD

**Issue by JuanFdS** [Fanny-Pack-Studios/endless-game-kit-2d#23]
Tareas:
- [x] Tener un botón desde la página principal que lleve a una escena de créditos.
- [x] Al terminar o saltear los créditos, se debería volver a la página principal.

En los créditos deberíamos mencionar:

Desarrolladores
- Jhan Pool Anibal Huayre Mauricio
- Ysamar Aracely Balcazar Ríos
- Juan Manuel Fernandes dos Santos

Producción
- Laura Foglia

Assets:
- Pixel Frog's Tiny Swords: https://pixelfrog-assets.itch.io/tiny-swords
- Miguel Gonzalez's Godot Gamejam template: https://github.com/bitbrain/godot-gamejam

Contribución conjunta
- Endless OS Fundation
- Fanny Pack Studios
- UTP (Universidad Tecnológica de Perú)

**Comment by YsaLuna** [comment]
Colaboradores de producción: Fanny Pack Studio y Endless
Contribución conjunta de Fanny Pack Studio y Endless

**Comment by JuanFdS** [comment]
Lau mando un par de maneras más:
> denominarse "Acknowledgements" o "Special Thanks". A veces también aparece bajo títulos como "In Association With", "Produced In Cooperation With", "With the Support Of", o "Sponsored By", dependiendo de la naturaleza de la colaboración o financiación.

**Comment by YsaLuna** [comment]
Sugerir más frases para decirle al jugador...
