### ISSUE TITLE
Que la camara siga al jugador

### ISSUE THREAD

**Issue by JuanFdS** [Fanny-Pack-Studios/endless-game-kit-2d#36]
Si el mapa es más grande que el jugador, podemos salirnos de pantalla ❗ .

Se necesita:
- [x] Cámara que siga al jugador.
~~- [ ] Idealmente, la cámara debería ser parte de `player.tscn` en vez de estar en un nivel en particular, así funciona para todos los niveles por defecto.~~ EDIT: vamos a configurar la cámara por nivel, así en algunos como el laberinto puede estar de más cerca y en otros (cómo en los créditos) puede estar de más lejos.
- [x] Se puede experimentar con las propiedades de la cámara `Position Smoothing` y `Drag`

# Ejemplo del resultado esperado:

## Antes

https://github.com/user-attachments/assets/3a50489c-7c03-4d72-ad0c-87a084c4eea8

## Después

https://github.com/user-attachments/assets/05e45cb5-078f-42bd-b841-dcb3a72e821c

**Comment by jphm22** [comment]
Hice la camara del personaje dentro de la escena del laberinto para probar las medidas del zoom de la camara, esta activado el smoothing y el drag. Si se confirma las medidas del zoom lo paso al player.tscn
