### ISSUE TITLE
Interfaz de la pantalla inicial

### ISSUE THREAD

**Issue by JuanFdS** [Fanny-Pack-Studios/endless-game-kit-2d#40]
Modificar la pantalla principal del juego para que tenga la estética de Tiny Swords.

Ahora se ve así:
![Image](https://github.com/user-attachments/assets/ff4d3ffd-bc3d-4c2d-8fb9-f8c5a24c66cf)

**Comment by YsaLuna** [comment]
![Image](https://github.com/user-attachments/assets/8c50f396-1e0b-4a1f-8893-7c6cac9afe41)
Otra forma de hacer usando  Parallax
