### ISSUE TITLE
Poder cerrar el inventario con la tecla Escape

### ISSUE THREAD

**Issue by JuanFdS** [Fanny-Pack-Studios/endless-game-kit-2d#64]
Ahora mismo solo se puede cerrar el inventario con la tecla I y apretando la cruz con el mouse.

- [x] Poder cerrarlo también con Esc.

**Comment by YsaLuna** [comment]
![Image](https://github.com/user-attachments/assets/bb010023-3756-42b0-bdae-dbcd011e9949)
